Parte2/IDEIMusic/IDEIMusic/Models/Disco.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace IDEIMusic.Models
{
    public class Disco
    {
        public int DiscoID { get; set; }
        public string Titulo { get; set; }
        public string Artista { get; set; }

        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:0}", ApplyFormatInEditMode = true)]
        [Display(Name = "Preço")]
        public decimal Preco { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "Quantidade deve ser um número positivo.")]
        public int Quantidade { get; set; }
    }
}

Parte2/IDEIMusic/IDEIMusic/Controllers/DiscoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IDEIMusic.Models;
using IDEIMusic.DAL;
using PagedList;

namespace IDEIMusic.Controllers
{
    public class DiscoController : Controller
    {
        private EditoraContext db = new EditoraContext();

        //
        // GET: /Disco/

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;

            ViewBag.TituloSortParm = String.IsNullOrEmpty(sortOrder) ? "Titulo_desc" : "";
            ViewBag.ArtistaSortParm = sortOrder == "Artista" ? "Artista_desc" : "Artista";
            ViewBag.PrecoSortParm = sortOrder == "Preco" ? "Preco_desc" : "Preco";
            ViewBag.QuantidadeSortParm = sortOrder == "Quantidade" ? "Quantidade_desc" : "Quantidade";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var discos = from d in db.Discos select d;

            if (!String.IsNullOrEmpty(searchString))
            {
                discos = discos.Where(s => s.Titulo.ToUpper().Contains(searchString.ToUpper())
                                       || s.Artista.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "Titulo_desc":
                    discos = discos.OrderByDescending(s => s.Titulo);
                    break;
                case "Artista":
                    discos = discos.OrderBy(s => s.Artista);
                    break;
                case "Artista_desc":
                    discos = discos.OrderByDescending(s => s.Artista);
                    break;
                case "Preco":
                    discos = discos.OrderBy(s => s.Preco);
                    break;
                case "Preco_desc":
                    discos = discos.OrderByDescending(s => s.Preco);
                    break;
                case "Quantidade":
                    discos = discos.OrderBy(s => s.Quantidade);
                    break;
                case "Quantidade_desc":
                    discos = discos.OrderByDescending(s => s.Quantidade);
                    break;
                default:
                    discos = discos.OrderBy(s => s.Titulo);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(discos.ToPagedList(pageNumber, pageSize));
        }

        //
        // GET: /Disco/Details/5

        public ActionResult Details(int id = 0)
        {
            Disco disco = db.Discos.Find(id);
            if (disco == null)
            {
                return HttpNotFound();
            }
            return View(disco);
        }

        //
        // GET: /Disco/Create
        [Authorize(Roles = "Gestor")]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Disco/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Titulo, Artista, Quantidade, Preco")]Disco disco)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Discos.Add(disco);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }                
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name after DataException and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(disco);
        }

        //
        // GET: /Disco/Edit/5
        [Authorize(Roles = "Gestor")]
        public ActionResult Edit(int id = 0)
        {
            Disco disco = db.Discos.Find(id);
            if (disco == null)
            {
                return HttpNotFound();
            }
            return View(disco);
        }

        //
        // POST: /Disco/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DiscoID, Titulo, Artista, Quantidade, Preco")]Disco disco)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(disco).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name after DataException and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(disco);
        }

        //
        // GET: /Disco/Delete/5
        [Authorize(Roles = "Gestor")]
        public ActionResult Delete(bool? saveChangesError = false, int id = 0)
        {
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persists see your system administrator.";
            }
            Disco disco = db.Discos.Find(id);
            if (disco == null)
            {
                return HttpNotFound();
            }
            return View(disco);
        }

        //
        // POST: /Disco/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Disco disco = db.Discos.Find(id);
                db.Discos.Remove(disco);
                db.SaveChanges();
            }
            catch (DataException/* dex */)
            {
                // uncomment dex and log error. 
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Parte2/IDEIMusic/IDEIMusic/Views/Disco/Create.cshtml
@model IDEIMusic.Models.Disco

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Disco</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Titulo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Titulo)
            @Html.ValidationMessageFor(model => model.Titulo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Artista)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Artista)
            @Html.ValidationMessageFor(model => model.Artista)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Preco)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Preco)
            @Html.ValidationMessageFor(model => model.Preco)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Quantidade)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Quantidade)
            @Html.ValidationMessageFor(model => model.Quantidade)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Parte2/IDEIMusic/IDEIMusic/Views/Disco/Delete.cshtml
@model IDEIMusic.Models.Disco

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Disco</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Titulo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Titulo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Artista)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Artista)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Preco)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Preco)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Quantidade)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Quantidade)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Parte2/IDEIMusic/IDEIMusic/Views/Disco/Details.cshtml
@model IDEIMusic.Models.Disco

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Disco</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Titulo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Titulo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Artista)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Artista)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Preco)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Preco)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Quantidade)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Quantidade)
    </div>
</fieldset>
<p>
    @if (Roles.IsUserInRole("Gestor"))
    {
       @Html.ActionLink("Edit", "Edit", new { id=Model.DiscoID })<text>|</text>
    }
    @Html.ActionLink("Back to List", "Index")
</p>

Parte2/IDEIMusic/IDEIMusic/Views/Disco/Edit.cshtml
@model IDEIMusic.Models.Disco

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Disco</legend>

        @Html.HiddenFor(model => model.DiscoID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Titulo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Titulo)
            @Html.ValidationMessageFor(model => model.Titulo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Artista)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Artista)
            @Html.ValidationMessageFor(model => model.Artista)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Preco)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Preco)
            @Html.ValidationMessageFor(model => model.Preco)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Quantidade)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Quantidade)
            @Html.ValidationMessageFor(model => model.Quantidade)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Parte2/IDEIMusic/IDEIMusic/Views/Disco/Index.cshtml
@model PagedList.IPagedList<IDEIMusic.Models.Disco>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Discos";
}

<h2>@ViewBag.Title</h2>

@if (Roles.IsUserInRole("Gestor")) 
{ 
<p>
    @Html.ActionLink("Create New", "Create")
</p>
}

@using (Html.BeginForm("Index", "Disco", FormMethod.Get))
{
    <p>
        Procurar por título ou artista: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<table>
    <tr>
        <th>
            @Html.ActionLink("Título", "Index", new { sortOrder = ViewBag.TituloSortParm })
            @*Html.DisplayNameFor(model => model.Titulo)*@
        </th>
        <th>
            @Html.ActionLink("Artista", "Index", new { sortOrder = ViewBag.ArtistaSortParm })
            @*Html.DisplayNameFor(model => model.Artista)*@
        </th>
        <th>
            @Html.ActionLink("Preço", "Index", new { sortOrder = ViewBag.PrecoSortParm })
            @*Html.DisplayNameFor(model => model.Preco)*@
        </th>
        <th></th>
        <th>
            @Html.ActionLink("Quantidade", "Index", new { sortOrder = ViewBag.QuantidadeSortParm })
            @*Html.DisplayNameFor(model => model.Quantidade)*@
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Artista)
        </td>
        <td>
            @(Html.DisplayFor(modelItem => item.Preco) + " €")
        </td>
        <td></td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantidade)
        </td>
        <td>
            @if (Roles.IsUserInRole("Gestor"))
            {
                @Html.ActionLink("Edit", "Edit", new { id=item.DiscoID })<text>|</text>
                @Html.ActionLink("Details", "Details", new { id = item.DiscoID }) <text>|</text>
                @Html.ActionLink("Delete", "Delete", new { id=item.DiscoID })
            } else
            {
                @Html.ActionLink("Details", "Details", new { id = item.DiscoID })
            }
            
        </td>
    </tr>
}
</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))